#!/usr/bin/env bash

set -euo pipefail
echo "Running pre-commit hook..."


readonly TLD="$(git rev-parse --show-toplevel)"
readonly VENV_STATUS="${VIRTUAL_ENV:-N/A}"
readonly SMOKE_TEST_DIR="$TLD/tests/smoke/"
readonly LOGS_DIR="$TLD/logs"

echo "Git toplevel directory is $TLD"

[[ -z $TLD ]] && echo "git rev-parse --show-toplevel couldn't find toplevel dir?!" && exit 1
[[ "$VENV_STATUS" == "N/A" ]] && (
    source "$TLD/venv/bin/activate"
    python3 -m pytest "$SMOKE_TEST_DIR" | tee "$LOGS_DIR/tests_$(date +%H_%M_%S).log"
)

echo "Success!"
